require('./alias/alias');
require('./event/event');
require('./format/format');
require('./highlight/highlight');
require('./ie-shiv/ie-shiv');
require('./include/include');
require('./indeterminate/indeterminate');
require('./inflector/inflector');
require('./jq/jq');
require('./keypress/keypress');
require('./mask/mask');
require('./reset/reset');
require('./route/route');
require('./scroll/scroll');
require('./scrollfix/scrollfix');
require('./showhide/showhide');
require('./unique/unique');
require('./uploader/uploader');
require('./validate/validate');

angular.module('ui.utils',  [
  'ui.event',
  'ui.format',
  'ui.highlight',
  'ui.include',
  'ui.indeterminate',
  'ui.inflector',
  'ui.jq',
  'ui.keypress',
  'ui.mask',
  'ui.reset',
  'ui.route',
  'ui.scrollfix',
  'ui.scroll',
  'ui.scroll.jqlite',
  'ui.showhide',
  'ui.unique',
  'ui.validate'
]);
